name: CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v3
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Test Run
      run: |
        npm ci
        npm run docs-generate
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
